### ISSUE TITLE
"Show Conversations" inside the three dots does nothing

### ISSUE THREAD

**Issue by i207M** [Christopher-Hayes/vscode-chatgpt-reborn#10]
### Describe the Bug

- Install the extension
- Chat with it for multiple conversations
- Hit "Show Conversations"
- Nothing happened

Expect: somewhere showing history chats

OS: Windows 10
VS Code: 1.76.2

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

I use OpenAI API Key method with gpt-3.5-turbo model.

**Comment by Christopher-Hayes** [comment]
Thank you for the bug report @i207M.

So, "Conversations" was a ChatGPT browser thing. Gencay removed the browser code before open-sourcing so that's expected not to work. In the next release, I'll be removing that button.

I do plan to re-introduce multiple chats, but the API doesn't give access to ChatGPT conversations. So, the re-introduction of multiple chats will be limited to the computer you are creating the chat on.
