### ISSUE TITLE
[Feature Request] Support to use Azure OpenAI API

### ISSUE THREAD

**Issue by PeterDaveHello** [Christopher-Hayes/vscode-chatgpt-reborn#28]
### Describe the feature

OpenAI's capacity/stability is somehow not stable enough due to the [high demand](https://www.reddit.com/r/OpenAI/comments/12b57q4/openai_has_temporarily_stopped_selling_the_plus/), also, it has some geo-location based restriction, Azure OpenAI seems to be a good alternative, will be nice if we could easily switch to use Azure OpenAI API. Thanks!

Reference:
- https://azure.microsoft.com/en-us/products/cognitive-services/openai-service/
- https://azure.microsoft.com/en-us/blog/chatgpt-is-now-available-in-azure-openai-service/

**Comment by Christopher-Hayes** [comment]
Pushed an update (`v3.16.4`) today to allow api key verification to work better with proxy endpoints. This may allow Azure to work if you use an azure `apiBaseUrl`.

Azure's OpenAI Service is "general availability", but they're still only giving access to for-profit companies. Individuals and open-source developers are being rejected. So, I won't be able to test until they open it up to the open-source community.

**Comment by Christopher-Hayes** [comment]
I took a deeper look into supporting Azure's OpenAI service.

Azure is a bit more complicated that just supporting a proxy OpenAI API, Azure's API is slightly different. The Azure user will need to make a separate deployment for each model they want to use. In this extension, we'll have to "remember" the IDs for each deployment if we want to offer any kind of model switching capability. (And because of this) Azure does not support the /models endpoint, which means the extension will have to do some things differently specifically for Azure.

[Azure has their own OpenAI library](https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/openai/openai) for working with their API. So, that will make things easier, it's just refactoring this extension to support this different architecture will take a little time.

For now, I'd recommend users try to make OpenAI's API work or [use a proxy of the OpenAI API](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn#proxy).

My personal experience setting up Azure's OpenAI API for testing demonstrated to me they don't seem ready for wide adoption. You have to go through a Microsoft Form to get access, getting access requires info about "your business" that will use this API, including your business's mailing address, the Azure interface for this service broke several times in the process of getting it setup with a single deployment. I can't imagine end users going through all that, I'm kind of surprised there's been several requests for Azure API support. But, I understand Azure might be the only option for some users, so I intend to eventually ship Azure API support, but it will take a little time to rearrange some parts of this extension.

**Comment by PeterDaveHello** [comment]
@Christopher-Hayes not sure what's happening right now, but the process I went through was fine, would like to provide some help if needed ;)

**Comment by Christopher-Hayes** [comment]
> @Christopher-Hayes not sure what's happening right now, but the process I went through was fine, would like to provide some help if needed ;)

Ah okay, good to know. So, you're saying your `apiBaseUrl` is something like `https://example-with-azure-openai.openai.azure.com/openai/deployments/your-deployment-name`, and with that you're able to use Azure? I guess that means Azure is able to ignore the fact that we send it a `model` param. And that means you don't use the model dropdown right?

**Comment by Christopher-Hayes** [comment]
Or wait, do you mean the process of setting up Azure was without issue? Gotcha, for whatever reason I ran into issues.

**Comment by PeterDaveHello** [comment]
@Christopher-Hayes awesome & congrats!!!

**Comment by Christopher-Hayes** [comment]
To give an update on this, so I think the way to go is for us to switch to using [Vercel's AI package](https://sdk.vercel.ai/docs) for the API provider logic. We still have to make some tweaks to support Azure's deployment flow, but switching to `ai` will allow us to support "Hugging Face, Anthropic (Claude), and LangChain" as well (without needing to use proxies for those).

**Comment by Christopher-Hayes** [comment]
Azure OpenAI API support added in `v3.24.0`. For Azure, you need to specify the "endpoint", the "deployment ID", and the "API version".

More, info in the release discussion: #74
