### ISSUE TITLE
Make gpt-3.5-turbo-16k available for chatgpt reborn

### ISSUE THREAD

**Issue by grizzlybearg** [Christopher-Hayes/vscode-chatgpt-reborn#39]
### Describe the feature

OpenAI released new models today and it's of interest to have these models available in the extension

**Comment by raphael2692** [comment]
i'll try to fork it and add this feature

**Comment by timkrase** [comment]
To anyone considering working on an upgrade: The [**api-provider.ts**](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/blob/157d6b32436000e343f885c41e044714429f4eec/src/api-provider.ts#L195) file makes use of [@dqbd/tiktoken](https://github.com/dqbd/tiktoken) to get the right encoding for the model and count the characters. 

This library is still missing the newest models in its bindings so you'll also have to change [this line](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/blob/157d6b32436000e343f885c41e044714429f4eec/src/api-provider.ts#L195) to get it to work. Otherwise the chat will always fail with an "invalid model" error. I've changed it locally to just use the gpt-3.5-turbo model for the encodings and character countings as it's the same encoding anyway. Wouldn't use this as the official solution though, so I'm not going to open a PR for this extension right now. There's already [a PR for tiktoken](https://github.com/dqbd/tiktoken/pull/53) to get the new models and afterwards updating this extension should be as easy as adding the models to the config.

**Comment by raphael2692** [comment]
thanks for the update @timkrase

**Comment by rambalachandran** [comment]
@raphael2692 looks like tiktoken PR is now merged. Will it be possible for you to modify the code to include gpt3.5-turbo-16k into the codebase

**Comment by raphael2692** [comment]
@rambalachandran I made it, let me know if it is ok :) https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/pull/40

**Comment by Christopher-Hayes** [comment]
Sorry missed this issue, while helping on the 16k PR for this extension, I came to the same conclusion as @timkrase. With the latest release of this extension, it's using the standard `gpt-3.5-turbo` for token counting the 16k model. 

After digging into this more, it seems the tiktoken NPM package that this extension uses, [@dqdb/tiktoken](https://www.npmjs.com/package/@dqbd/tiktoken), is no longer receiving new releases (It's still on v1.0.7). However, it looks like [tiktoken](https://www.npmjs.com/package/tiktoken) is the new location of tiktoken releases (since it's on v1.0.10). Next release, I'll try to fit in moving over to that package.

**Comment by Christopher-Hayes** [comment]
:rocket: `v3.17.0` of this extension now has the 16k model.

**Comment by grizzlybearg** [comment]
@Christopher-Hayes Thanks for this.
