### ISSUE TITLE
Can Azure OpenAI Endpoint Work?

### ISSUE THREAD

**Issue by rambalachandran** [Christopher-Hayes/vscode-chatgpt-reborn#55]
### Describe the feature

Given the current turmoil at OpenAI, can we change the `Api Base Url` in settings to Azure endpoint and will it work? Will like to get a confirmation before creating an Azure account.

**Comment by Christopher-Hayes** [comment]
This has been a work-in-progress. So, not yet.

The main blocker is that Azure handles models differently. You get a separate endpoint for each model. I'll try to get this finished off in the next month or so.

If you badly want to use another service, you can use one of the "openai proxies" available on github, where you can use any service (Anthropic, Azure, etc) and the proxy converts API requests between the OpenAI format and the Azure/Anthropic/etc format. You would have to host that yourself though and may have bugginess I probably can't help with.

**Comment by rambalachandran** [comment]
Thank you @Christopher-Hayes . I will give the openai proxies a try for now. Happy to test the Azure implementation once you think it is ready.

**Comment by ChuckJonas** [comment]
All that's really needed here is the ability to:

1. Set the `api-key` header instead of `Authorization: "Bearer`
2. Apply the API key version URL param `?api-version={{api-version}}`

The extension should at least then work for `/chat/completion` use cases... Which I imagine is pretty much everything at this point?  Even co-pilot is apparently using GPT-4 for it's code completions now

**Comment by Christopher-Hayes** [comment]
Azure OpenAI API support added in `v3.24.0`. For Azure, you need to specify the "endpoint", the "deployment ID", and the "API version".

More, info in the release discussion: #74
